image: ubuntu/latest
packages:
  - reprotest
sources:
  - https://github.com/strugee/filter-other-days
tasks:
  - setup: |
      cd filter-other-days
      gpg --import misc/test-keys.gpg
      patch release.sh misc/srht-release.patch
  - test: |
      cd filter-other-days
      reprotest ./release.sh filter-other-days_.tar{,.gz,.xz}

