language: generic
os:
  - linux
  - osx
dist: trusty
addons:
  apt:
    packages:
    - faketime
    - colordiff
    - devscripts
    - fakeroot
    - debhelper
    - lintian
services:
  - docker
install:
script:
  - ./test/run-tests.sh
  - patch filter-other-days freebsd-bug-237752-hack.patch
  - ./test/run-tests.sh
  - if [ $TRAVIS_OS_NAME = osx ]; then travis_terminate 0; fi
  - sudo apt-get remove -qq faketime
  - ./test/run-tests.sh
  - checkbashisms --newline --posix --extra filter-other-days
  # We patched for FreeBSD earlier and dpkg-buildpackage complains if the working directory is dirty
  - git checkout filter-other-days
  - dpkg-buildpackage
  - lintian --pedantic ../filter-other-days_*_all.deb
  # reprotest
  - docker run --privileged --mount type=bind,source=$(pwd),destination=/mnt -w /mnt ubuntu:latest sh -c 'apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -qq install git reprotest && patch release.sh misc/travis-release.patch && reprotest -s . "export GNUPGHOME=$(pwd)/.gnupg; ./release.sh 5000; rm -r \$GNUPGHOME || true" "filter-other-days_5000.tar filter-other-days_5000.tar.gz filter-other-days_5000.tar.xz filter-other-days_freebsd_5000.tar filter-other-days_freebsd_5000.tar.gz filter-other-days_freebsd_5000.tar.xz"'
