language: none
dist: trusty
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq faketime
  - sudo apt-get install -qq colordiff
  - sudo apt-get install -qq devscripts
script: ./test/run-tests.sh && checkbashisms --newline --posix --extra filter-other-days
