.\" filter-other-days.1
.\"
.\" filter-other-days(1) manual page
.\"
.\" Copyright 2017, 2018, 2019 AJ Jordan <alex@strugee.net>
.\"
.\" This file is part of filter-other-days.
.\"
.\" filter-other-days is free software: you can redistribute it and/or
.\" modify it under the terms of the GNU Affero General Public License
.\" as published by the Free Software Foundation, either version 3 of
.\" the License, or (at your option) any later version.
.\"
.\" filter-other-days is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" Affero General Public License for more details.
.\"
.\" You should have received a copy of the GNU Affero General Public
.\" License along with filter-other-days.  If not, see
.\" <https://www.gnu.org/licenses/>.
.Dd September 2, 2018
.Dt FILTER-OTHER-DAYS 1
.Os
.Sh NAME
.Nm filter-other-days
.Nd filter logfiles for today's date in an Artificial Ignorance-compatible way
.Sh SYNOPSIS
.Nm
.Op Fl d Ar seconds
.Sh DESCRIPTION
The
.Nm
utility filters logfiles for today's date in an Artificial Ignorance-compatible way.
That is, it only throw away entries that it's sure
.Em aren't
from today.
This is implemented by using
.Li grep -v
on other dates instead of
.Li grep
on today's date.
The rationale here is that it's better to receive irrelevant information than it is to miss relevant information.
.Pp
.Nm
accepts input on stdin only.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl d Ar seconds
Treat
.Ar seconds
as the current time, in seconds since the epoch.
Not available on all systems; availability is determined at runtime.
.It Fl -help , h
Print help.
.It Fl -version , v
Print version.
.El
.Sh EXIT STATUS
.Ex -std
Matching zero lines is not considered an error.
.Sh EXAMPLES
Filter logfile for entries from today:
.Bd -literal -offset Dl
filter-other-days < logfile
.Ed
.Pp
Filter daemon.log and syslog.log for entries from today:
.Bd -literal -offset Dl
cat daemon.log syslog.log | filter-other-days
.Ed
.Sh AUTHORS
.An AJ Jordan Aq Mt alex@strugee.net
.Sh CAVEATS
.Nm
computes today's date at startup.
If the time rolls over to a new day during execution, this will not be accounted for.
.Sh BUGS
Bugs are tracked in GitHub:
.Lk https://github.com/strugee/filter-other-days/issues
.Pp
There are surely many, many styles of logfile timestamps that
.Nm
does not recognize.
If you encounter such a style, please file a bug.
.Pp
.Nm ,
except
.Nm
.Fl d ,
is designed to require only POSIX but was tested on systems with extensions to POSIX.
There may be implicit dependencies on these extensions lurking in the codebase; if
.Nm
.Em should
run on your system, but does not, please file a bug.
.Pp
.Fl d
is not compatible with purely POSIX systems because it is impossible to implement using only what POSIX provides.
